baseURL = 'https://kukudely.github.io/'
locale = 'en-us'
title = "kukudely's Space"
theme = 'kukudely'

[menu]
  [[menu.main]]
  name = 'about'
  url = '/about/'
  weight = 1

  [[menu.main]]
  name = 'posts'
  url = '/posts/'
  weight = 2
